name: Deploy Template   

on:
 workflow_call:
  inputs:
    app-name:
        required: true
        type: string
    app-folder:
        required: true
        type: string
    python-version:
        required: false
        type: string
        default: "3.9"
    environment:
        required: true
        type: string    
  secrets:
    azure-credentials:
        required: true
env:
  AZURE_SLOT_RED: red  
  
jobs:
  deploy-template:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0                     
        # - name: Check if folder has changes
        #   id: check_changes
        #   run: |
        #     if git diff --name-only HEAD~1 HEAD | grep -q "^${{ inputs.app-folder }}/"; then
        #       echo "Folder ${{ inputs.app-folder }} has changes."
        #       echo "deploy=true" >> $GITHUB_ENV
        #     else  
        #       echo "No changes in ${{ inputs.app-folder }}."
        #       echo "deploy=false" >> $GITHUB_ENV 
        #     fi   
            
        # - name: Skip Deployment if No Changes
        #   if: env.deploy == 'false'
        #   run: |
        #    echo "No changes detected in the folder. Skipping deployment."
        #    exit 0          
     
        - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
          # if: env.deploy == 'true'
          uses: actions/setup-python@v4
          with:
            python-version: ${{ inputs.python-version }}
    
        - name: 'Resolve Project Dependencies Using Pip'
          # if: env.deploy == 'true'
          shell: bash
          run: |
            cd ${{ inputs.app-folder }}
            python -m pip install --upgrade pip
            pip install -r requirements.txt --target=".python_packages/lib/site-packages"
  
        - name: 'Login via Azure CLI'
          # if: env.deploy == 'true'
          uses: azure/login@v1
          with:
            creds: ${{ secrets.azure-credentials}}

        # - name: Deploy to red Slot
        #   uses: azure/functions-action@v1
        #   with:
        #    app-name: ${{ inputs.app-name }}
        #    slot-name: ${{ env.AZURE_SLOT_RED }}
        #    package: ./${{ inputs.app-folder }}  
  
        - name: Deploy to Azure Function App
          # if: env.deploy == 'true'
          uses: azure/functions-action@v1
          with:
            app-name: ${{ inputs.app-name }}
            package: ./${{ inputs.app-folder }}
            scm-do-build-during-deployment: true
            enable-oryx-build: true
  # manual_approval:
  #   needs: deploy-template
  #   runs-on: ubuntu-latest
  #   environment: ${{ inputs.environment }}
  #   steps:
  #   - name: Awaiting Manual Approval
  #     run: echo "Awaiting approval to proceed with swapping slots."

  # swap:
  #   needs: manual_approval
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Login to Azure
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.azure-credentials}}
  #   - name: Set Resource Group Name
  #     run: |
  #      # Extract or construct the resource group name
  #      RESOURCE_GROUP=$(az functionapp list --query "[?name=='fn-cicd-dev1'].{ResourceGroup:resourceGroup}" -o tsv)
  #       echo "RESOURCE_GROUP=${RESOURCE_GROUP}" >> $GITHUB_ENV   
  #   - name: Debug Variables
  #     run: |
  #       echo "App Name: ${{ inputs.app-name }}"
  #       echo "Resource Group: $RESOURCE_GROUP"

  #   - name: Swap red Slot with Production
  #     # uses: azure/azure-cli-action@v1
  #     # with:
  #     #   inlineScript: |
  #     run: |
  #         az functionapp deployment slot swap \
  #           --name ${{ inputs.app-name }} \
  #           --resource-group $RESOURCE_GROUP \
  #           --slot ${{ env.AZURE_SLOT_RED }}
        
