name: Sync Specific Folders and Deploy

on:
  workflow_dispatch: # Allows manual triggering of the workflow
      inputs:
        # folders:
        #   description: "Comma-separated list of folders to deploy"
        #   required: true
        fn-dev1:
          description: "Deploy fn-dev1?"
          required: false
          default: false
          type: boolean
        fn-dev2:
          description: "Deploy fn-dev2?"
          required: false
          default: false
          type: boolean
        source_branch:
          description: "Source branch to sync from (e.g., develop, qa)"
          required: true
          default: "develop" # Optional default value
        target_branch:
          description: "Target branch to sync to (e.g., qa, main)"
          required: true
          default: "qa" # Optional default value
      # folders:
      #   description: "Comma-separated list of folders to sync (e.g., folder1,folder2)"
      #   required: true
      #   default: "folder1,folder2" # Optional default value

permissions:
  contents: write
  
jobs:
  sync-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure all branches are fetched

      - name: Determine Selected Folders
        id: select-folders
        run: |
          FOLDERS=""
          if [ "${{ github.event.inputs.fn-dev1 }}" == "true" ]; then
            FOLDERS="$FOLDERS fn-dev1"
          fi
          if [ "${{ github.event.inputs.fn-de2 }}" == "true" ]; then
            FOLDERS="$FOLDERS fn-dev2"
          fi
          echo "FOLDERS=$FOLDERS" >> $GITHUB_ENV

      - name: Use Selected Folders
        run: |
          echo "Selected folders: $FOLDERS" 

      # Step 2: Parse Inputs
      - name: Parse Inputs
        id: parse-inputs
        run: |
          # echo "FOLDERS=$(echo '${{ github.event.inputs.folders }}' | tr ',' ' ')" >> $GITHUB_ENV
          echo "SOURCE_BRANCH=${{ github.event.inputs.source_branch }}" >> $GITHUB_ENV
          echo "TARGET_BRANCH=${{ github.event.inputs.target_branch }}" >> $GITHUB_ENV

      - name: Debug Current Branch
        run: |
         echo "Current branch:"
         git branch --show-current
      - name: Debug Remote Branches
        run: |
         echo "Remote branches:"
         git branch -r
               
      - name: Ensure Branches Exist
        run: |
         git fetch origin $SOURCE_BRANCH
         git fetch origin $TARGET_BRANCH             

      # Step 3: Switch to Target Branch
      - name: Switch to Target Branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout $TARGET_BRANCH

      # Step 4: Copy Specific Folders from Source Branch
      - name: Copy Specific Folders
        run: |
          for folder in $FOLDERS; do
            echo "Checking out $folder from $SOURCE_BRANCH..."
            git checkout origin/$SOURCE_BRANCH -- "$folder" || (echo "Error checking out $folder" && exit 1)
          done
          git add $FOLDERS
          git commit -m "Sync $FOLDERS from $SOURCE_BRANCH to $TARGET_BRANCH" || echo "No changes to commit"
          git push origin $TARGET_BRANCH


